const rooms = [
    {
        name:"SR-1",
        type:"smallRoom",
        price:56,
        maxPeople:2,
        image:'https://i.ibb.co/QcXzhsr/small1.jpg',
        bookingStatus:false

    },
    {
        name:"SR-2",
        type:"smallRoom",
        price:59,
        maxPeople:2,
        image:'https://i.ibb.co/7NyfpyW/small2.jpg',
        bookingStatus:false
    },
    {
        name:"SR-3",
        type:"smallRoom",
        price:62,
        maxPeople:3,
        image:'https://i.ibb.co/2YQ8fJg/small3.jpg',
        bookingStatus:false
    },
    {
        name:"SR-4",
        type:"smallRoom",
        price:66,
        maxPeople:3,
        image:'https://i.ibb.co/JHPvNNG/small4.jpg',
        bookingStatus:false
    },
    {
        name:"LR-1",
        type:"luxuryRoom",
        price:68,
        maxPeople:2,
        image:'https://i.ibb.co/j32mg5b/luxury1.jpg',
        bookingStatus:false
    },
    {
        name:"LR-2",
        type:"luxuryRoom",
        price:72,
        maxPeople:2,
        image:'https://i.ibb.co/ScGtYwD/luxury2.jpg',
        bookingStatus:false
    },
    {
        name:"LR-3",
        type:"luxuryRoom",
        price:76,
        maxPeople:3,
        image:'https://i.ibb.co/2hM3bbW/luxury3.jpg',
        bookingStatus:false
    },
    {
        name:"LR-4",
        type:"luxuryRoom",
        price:80,
        maxPeople:3,
        image:'https://i.ibb.co/nsSryPW/luxury4.jpg',
        bookingStatus:false
    },
    {
        name:"AR-1",
        type:"apartmentRoom",
        price:83,
        maxPeople:3,
        image:'https://i.ibb.co/b6bCQ9b/apartement1.jpg',
        bookingStatus:false
    },
    {
        name:"AR-2",
        type:"apartmentRoom",
        price:89,
        maxPeople:4,
        image:'https://i.ibb.co/5ctzYYp/apartment2.jpg',
        bookingStatus:false
    },
    {
        name:"AR-3",
        type:"apartmentRoom",
        price:94,
        maxPeople:5,
        image:'https://i.ibb.co/gzHQ1Wb/apartment3.jpg',
        bookingStatus:false
    },
    {
        name:"AR-4",
        type:"apartmentRoom",
        price:99,
        maxPeople:6,
        image:'https://i.ibb.co/XYmj3db/apartment4.jpg',
        bookingStatus:false
    }
]


export {rooms as rooms}